################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/7shu.co/msp

  - &Org1
    Name: Org1MSP
    ID: Org1MSP

    MSPDir: crypto-config/peerOrganizations/org1.7shu.co/msp

    AnchorPeers:
      - Host: peer0.org1.7shu.co
        Port: 7501

  - &Org2
    Name: Org2MSP
    ID: Org2MSP

    MSPDir: crypto-config/peerOrganizations/org2.7shu.co/msp

    AnchorPeers:
      - Host: peer0.org2.7shu.co
        Port: 7501

  - &Org3
    Name: Org3MSP
    ID: Org3MSP

    MSPDir: crypto-config/peerOrganizations/org3.7shu.co/msp

    AnchorPeers:
      - Host: peer0.org3.7shu.co
        Port: 7501

  - &Org4
    Name: Org4MSP
    ID: Org4MSP

    MSPDir: crypto-config/peerOrganizations/org4.7shu.co/msp

    AnchorPeers:
      - Host: peer0.org4.7shu.co
        Port: 7501

  - &Org5
    Name: Org5MSP
    ID: Org5MSP

    MSPDir: crypto-config/peerOrganizations/org5.7shu.co/msp

    AnchorPeers:
      - Host: peer0.org5.7shu.co
        Port: 7501

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

  OrdererType: kafka

  Addresses:
    - orderer0.7shu.co:7050
    - orderer1.7shu.co:7050
    - orderer2.7shu.co:7050

  BatchTimeout: 2s

  BatchSize:

    MaxMessageCount: 10

    AbsoluteMaxBytes: 98 MB

    PreferredMaxBytes: 512 KB

  Kafka:
    Brokers:
      - 192.168.31.211:9092
      - 192.168.31.212:9092
      - 192.168.31.213:9092
      - 192.168.31.214:9092

  Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

  Organizations:

Capabilities:
  Global: &ChannelCapabilities
    V1_1: true

  Orderer: &OrdererCapabilities
    V1_1: true

  Application: &ApplicationCapabilities
    V1_1: true

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

  TwoOrgsOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
          - *Org2
          - *Org3
          - *Org4
          - *Org5
  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
        - *Org3
        - *Org4
        - *Org5