version: '2'

services:

  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
    ports:
      - "9092:9092"
    extra_hosts:
      - "zookeeper1:192.168.31.201"
      - "zookeeper2:192.168.31.202"
      - "zookeeper3:192.168.31.203"
      - "kafka1:192.168.31.211"
      - "kafka2:192.168.31.212"
      - "kafka3:192.168.31.213"
      - "kafka4:192.168.31.214"